[package]
name = "redis-scanner"
version = "0.1.0"
authors = ["Alec Embke <aembke@gmail.com>"]
edition = "2018"
description = "A scanning utility for Redis."

[profile.release]
debug = true

[dependencies]
clap = { version = "2.33", features = ["yaml"] }
opentelemetry = { version = "0.13", features = ["rt-tokio", "trace"] }
opentelemetry-jaeger = { version = "0.12", features = ["tokio", "reqwest_collector_client"] }
tracing-attributes = "0.1"
tracing-opentelemetry = "0.12"
tracing-core = "0.1"
tracing-subscriber = "0.2"
tracing = "0.1"
log = "0.4"
pretty_env_logger = "0.4"
tokio = { version = "1.8", features = ["full"] }
futures = "0.3"

[dependencies.fred]
path = "../.."
features = ["ignore-auth-error"]
default-features = false

[features]
default = []
partial-tracing = ["fred/partial-tracing"]
full-tracing = ["fred/full-tracing"]